-- Create all prosperity tables

CREATE TABLE Tasks (
	ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Work` BIGINT NOT NULL,
	`Name` VARCHAR(500) NOT NULL,
	`Hours` INT NOT NULL
);

CREATE TABLE Work_Types (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Name` VARCHAR(50) NOT NULL
);

CREATE TABLE Works (
	ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Theme` INT NOT NULL,
	`Type` INT NOT NULL
);

CREATE TABLE Levels (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Name` VARCHAR(50) NOT NULL,
	`Description` VARCHAR(500) NOT NULL
);

CREATE TABLE Themes (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Topic` INT NOT NULL,
	`Level` INT NOT NULL,
	`No` INT NOT NULL,
	`Name` VARCHAR(500) NOT NULL,
	`Hours` INT NOT NULL
);

CREATE TABLE General_Mastering (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Discipline` INT NOT NULL,
	`Mastering` INT NOT NULL
);

CREATE TABLE General_Selection (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Theme` INT NOT NULL,
	`Mastering` INT NOT NULL
);

CREATE TABLE Professional_Mastering (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Discipline` INT NOT NULL,
	`Mastering` INT NOT NULL
);

CREATE TABLE Professional_Selection (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Theme` INT NOT NULL,
	`Mastering` INT NOT NULL
);

CREATE TABLE Theme_Plan (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Discipline` INT NOT NULL,
	`No` INT NOT NULL,
	`Name` VARCHAR(500) NOT NULL,
	`Hours` INT NOT NULL
);

CREATE TABLE Discipline_Codes (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Code` VARCHAR(15) NOT NULL
);

CREATE TABLE Disciplines (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Code` INT NOT NULL,
	`Name` VARCHAR(250) NOT NULL
);

CREATE TABLE Meta_data (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Discipline` INT NOT NULL,
	`Type` INT NOT NULL,
	`Name` VARCHAR(250) NOT NULL
);


CREATE TABLE Meta_types (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Name` VARCHAR(250) NOT NULL
);

CREATE TABLE Hours (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Discipline` INT NOT NULL,
	`WorkType` INT NOT NULL,
	`Count` INT NOT NULL
);

CREATE TABLE Source_Types (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Name` VARCHAR(250) NOT NULL
);

CREATE TABLE Sources (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Discipline` INT NOT NULL,
	`Type` INT NOT NULL,
	`Name` VARCHAR(1000) NOT NULL
);

CREATE TABLE Conformity (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Discipline` INT NOT NULL,
	`Speciality` INT NOT NULL
);

CREATE TABLE Speciality_Codes (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Code` VARCHAR(15) NOT NULL
);

CREATE TABLE Specialities (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Code` INT NOT NULL,
	`Name` VARCHAR(250) NOT NULL
);

CREATE TABLE General_Competetions (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Speciality` INT NOT NULL,
	`No` SMALLINT NOT NULL,
	`Name` VARCHAR(250) NOT NULL,
	`Knowledge` VARCHAR(1000) NOT NULL,
	`Skills` VARCHAR(1000) NOT NULL
);

CREATE TABLE Professional_Competetions (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`Speciality` INT NOT NULL,
	`No1` SMALLINT NOT NULL,
	`No2` SMALLINT NOT NULL,
	`Name` VARCHAR(250) NOT NULL,
	`Knowledge` VARCHAR(1000) NOT NULL,
	`Skills` VARCHAR(1000) NOT NULL,
	`Experience` VARCHAR(1000) NOT NULL
);

CREATE TABLE Redactors (
	`User` CHAR(32) NOT NULL DEFAULT '' PRIMARY KEY,
	`Pass` TINYINT UNSIGNED NOT NULL,
	`Host` CHAR(60) NOT NULL DEFAULT '',
	`Comment` VARCHAR(5000) NOT NULL DEFAULT '-'
);