-- reset auto increments

ALTER TABLE Meta_types AUTO_INCREMENT = 1;
ALTER TABLE Meta_data AUTO_INCREMENT = 1;
ALTER TABLE Disciplines AUTO_INCREMENT = 1;
ALTER TABLE Theme_Plan AUTO_INCREMENT = 1;
ALTER TABLE Themes AUTO_INCREMENT = 1;
ALTER TABLE Works AUTO_INCREMENT = 1;
ALTER TABLE Tasks AUTO_INCREMENT = 1;
ALTER TABLE Sources AUTO_INCREMENT = 1;
ALTER TABLE Source_types AUTO_INCREMENT = 1;
ALTER TABLE Hours AUTO_INCREMENT = 1;
ALTER TABLE Levels AUTO_INCREMENT = 1;

ALTER TABLE Conformity AUTO_INCREMENT = 1;

ALTER TABLE Specialities AUTO_INCREMENT = 1;
ALTER TABLE Speciality_codes AUTO_INCREMENT = 1;
ALTER TABLE General_competetions AUTO_INCREMENT = 1;
ALTER TABLE Professional_competetions AUTO_INCREMENT = 1;
ALTER TABLE General_mastering AUTO_INCREMENT = 1;
ALTER TABLE Professional_mastering AUTO_INCREMENT = 1;