ALTER TABLE Tasks MODIFY COLUMN `Hours` MEDIUMINT NOT NULL DEFAULT 0;
ALTER TABLE Themes MODIFY COLUMN `Hours` MEDIUMINT NOT NULL DEFAULT 0;
ALTER TABLE Theme_Plan MODIFY COLUMN `Hours` MEDIUMINT NOT NULL DEFAULT 0;
ALTER TABLE Hours MODIFY COLUMN `Count` MEDIUMINT NOT NULL DEFAULT 0;